### ISSUE TITLE
timer emits 'done' after reset()

### ISSUE THREAD

**Issue by brandonmp** [malinkie/node-timers#4]
i'd like to use a `countdown timer` to apply a timeout to a worker queue i'm building. if worker doesn't reset the timer by `n` milliseconds, the process is killed and a new one is spawned. 

am i doing this right? with the code below, the `done` event is emitted even after `reset()` is successfully called.  the `done` event seems to emit at the originally scheduled time, so it's as if `reset()` is having no effect

```
let countdown = require('node-timers/countdown')
let queueTimer = countdown({ startTime: 5000 })
    queueTimer.start()
    setTimeout(()=> {queueTimer.reset()}, 1500)
    queueTimer.on('reset', () => { console.log('reset', queueTimer.time()) ;queueTimer.start()})
    queueTimer.on('done', () => {
        console.log('done')
     })
```

**Comment by malinkie** [comment]
Currently out of town. i'll take a look this weekend. #notignoringyou :)

**Comment by brandonmp** [comment]
haha no rush @malinkie , thanks for a quick response

**Comment by malinkie** [comment]
Hey @brandonmp. I pulled in your code and increased the start time of the countdown timer to 10 seconds. I also increased your setTimeout to trigger a reset at 5 seconds rather than 1.5 seconds in.

The done event is triggering for me after the 15 seconds total (5sec -> reset -> 10 sec) What version of node / what os are you on?

i am assuming 6+ node use to the es6 usage...

I just added a test case to cover this usage. Please tell me if i am covering correctly :D
